/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Diagnostic {
  message: string
  line: number
  column: number
  severity: string
}

export interface ExtractedRule {
  className: string
  cssText: string
  layer: number
}

export declare function generateCss(rulesJson: string): string

/** Theme data passed from the Vite plugin (loaded from the TS theme package) */
export interface ThemeInput {
  /** JSON: { "blue": { "50": "#eff6ff", ... }, ... } */
  colors: string
  /** JSON: { "white": "#ffffff", ... } */
  namedColors: string
  /** JSON: { "0": "0px", "0.5": "0.125rem", ... } */
  spacing: string
  /** JSON: { "xs": { "fontSize": "0.75rem", "lineHeight": "1rem" }, ... } */
  textSizes: string
  /** JSON: { "thin": "100", "light": "300", ... } */
  fontWeights: string
  /** JSON: { "none": "0px", "sm": "0.125rem", "DEFAULT": "0.25rem", ... } */
  radii: string
  /** JSON: { "sm": "0 1px 2px ...", "DEFAULT": "0 1px 3px ...", ... } */
  shadows: string
  /** JSON: { "full": "100%", "screen": "100vw", ... } */
  sizes: string
  /** Default border-radius value */
  defaultRadius: string
  /** Default shadow value */
  defaultShadow: string
}

export declare function transform(code: string, filename: string, layerOffset: number, themeInput: ThemeInput, strict?: boolean | undefined | null): TransformOutput

export interface TransformOutput {
  code: string
  rules: Array<ExtractedRule>
  nextLayer: number
  hasDynamic: boolean
  diagnostics: Array<Diagnostic>
}
