export * as colors from './colors.ts'
export * as spacing from './spacing.ts'
export * as typography from './typography.ts'
export * as sizes from './sizes.ts'
export * as shadows from './shadows.ts'
export * as borders from './borders.ts'
