/** Cached reference to the `<style id="twc-theme">` element used by {@link injectTheme}. */
let themeStyleEl: HTMLStyleElement | null = null

/**
 * Injects theme CSS custom properties into the document.
 *
 * Creates (or reuses) a `<style id="twc-theme">` element in the document head
 * and appends the provided CSS text to it. Each call appends to the existing
 * content, so multiple themes can be injected sequentially.
 *
 * This function is a no-op in non-browser environments (SSR-safe).
 *
 * @param cssText - The CSS string to inject, typically the `cssText` property
 *   from a {@link ThemeResult} returned by {@link createTheme}.
 *
 * @example
 * ```ts
 * import { createTheme, injectTheme } from 'typewritingclass/theme'
 *
 * const light = createTheme({
 *   name: 'light',
 *   colors: { blue: { 500: '#3b82f6' } },
 * })
 *
 * const dark = createTheme({
 *   name: 'dark',
 *   colors: { blue: { 500: '#60a5fa' } },
 * })
 *
 * // Inject both themes into a single <style> element
 * injectTheme(light.cssText)
 * injectTheme(dark.cssText)
 * // <style id="twc-theme">
 * //   [data-theme="light"] { --twc-color-blue-500: #3b82f6; }
 * //   [data-theme="dark"]  { --twc-color-blue-500: #60a5fa; }
 * // </style>
 * ```
 */
export function injectTheme(cssText: string): void {
  if (typeof document === 'undefined') return

  if (!themeStyleEl) {
    themeStyleEl = document.createElement('style')
    themeStyleEl.id = 'twc-theme'
    document.head.appendChild(themeStyleEl)
  }

  // Append to existing theme styles
  themeStyleEl.textContent += (themeStyleEl.textContent ? '\n' : '') + cssText
}

/**
 * Activates a named theme by setting the `data-theme` attribute on the
 * document root element (`<html>`).
 *
 * The matching theme CSS must already be injected via {@link injectTheme}.
 * The active theme's custom properties will take effect for any rules using
 * `[data-theme="<name>"]` selectors generated by {@link createTheme}.
 *
 * This function is a no-op in non-browser environments (SSR-safe).
 *
 * @param name - The theme name to activate, matching the `name` used in
 *   {@link ThemeConfig} when calling {@link createTheme}.
 *
 * @example
 * ```ts
 * import { setTheme } from 'typewritingclass/theme'
 *
 * // Switch to the dark theme at runtime
 * setTheme('dark')
 * // <html data-theme="dark"> ...
 *
 * // Switch back to light
 * setTheme('light')
 * // <html data-theme="light"> ...
 * ```
 */
export function setTheme(name: string): void {
  if (typeof document === 'undefined') return
  document.documentElement.setAttribute('data-theme', name)
}
